### ISSUE TITLE
Issue in step3

### ISSUE THREAD

**Issue by javierhow** [mikarubi/voluseg#4]
Hi Mika,

There's an error in line 57 of step3:

`
Traceback (most recent call last):
  File "/nrs/ahrens/Javier/Code/processVideos_test_blocky.py", line 57, in <module>
    voluseg.step3_mask_volumes(parameters)
  File "/groups/ahrens/home/howj/.local/lib/python3.6/site-packages/voluseg/_steps/step3.py", line 57, in mask_volumes
    timepoints = np.range(p.lt)
AttributeError: module 'numpy' has no attribute 'range'
`

I think you meant to use np.arange, not np.range.

Best,
Javier

**Comment by mikarubi** [comment]
Thanks Javier, you are right.
Fixed!
Mika
