### ISSUE TITLE
JSON parameters file is made, but pickle is required

### ISSUE THREAD

**Issue by javierhow** [mikarubi/voluseg#44]
Hi!

The new version of voluseg makes a JSON file (parameters.json), but then `parameters = voluseg.load_parameters(filename_parameters)` throws an error because parameters.pickle does not exist. I fixed it by changing the following line in the example to require a JSON file, not a pickle file:

`filename_parameters = os.path.join(parameters0['dir_output'], 'parameters.pickle')`

Have you all moved on to using JSON files now, or can we still specify pickle?

Thanks!
Javier

**Comment by mikarubi** [comment]
Hi Javier,

voluseg is currently in active development. It may be easier to
continue using the older (stable) version for now, while we stabilize the
new development. We will try to maximize backwards compatibility so
hopefully you won't need to make too many changes.

Thanks!
Mika

**Comment by javierhow** [comment]
Thanks! Ok. Is there a simple way to reinstall an old version?

Also, would the results from the current version still be valid?

**Comment by mikarubi** [comment]
https://github.com/mikarubi/voluseg/releases/tag/2022

**Comment by javierhow** [comment]
Thanks. It keeps erroring:

`24/09/24 18:24:21 INFO TaskSetManager: Lost task 12.2 in stage 3.0 (TID 709) on 10.36.60.20, execu                                                                                        tor 25: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.p                                                                                        y", line 605, in main
    process()
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.p                                                                                        y", line 597, in process
    serializer.dump_stream(out_iter, outfile)
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializ                                                                                        ers.py", line 271, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/util.py"                                                                                        , line 107, in wrapper
    return f(*args, **kwargs)
  File "/groups/ahrens/home/howj/.local/lib/python3.9/site-packages/voluseg/_steps/step2.py", line                                                                                         118, in register_volume
    volume = volume.T
AttributeError: 'NoneType' object has no attribute 'T'
`

**Comment by mikarubi** [comment]
see slack.
