### ISSUE TITLE
Step 1 issue

### ISSUE THREAD

**Issue by javierhow** [mikarubi/voluseg#5]
Hi Mika,

Thanks for the last fix. There seems to be an error loading partially processed volumes in step 1:

`21/03/22 12:26:30 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 2, 10.36.110.40, executor 16): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 605, in main
    process()
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 595, in process
    out_iter = func(split_index, iterator)
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/pyspark/rdd.py", line 2596, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/pyspark/rdd.py", line 2596, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/pyspark/rdd.py", line 2596, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/pyspark/rdd.py", line 425, in func
    return f(iterator)
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/pyspark/rdd.py", line 860, in processPartition
    f(x)
  File "/groups/ahrens/home/howj/spark-3.0.1-bin-hadoop2.7/python/pyspark/util.py", line 107, in wrapper
    return f(*args, **kwargs)
  File "/groups/ahrens/home/howj/.local/lib/python3.6/site-packages/voluseg/_steps/step1.py", line 49, in initial_processing
    or load_volume(fullname_volume+ali+hdf):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

I think it's because you return the entire volume with `load_volume()` Maybe you meant `load_volume(fullname_volume+ali+hdf) is not None`.

Best,
Javier

**Comment by mikarubi** [comment]
yes, that's correct.
fixed!
