### ISSUE TITLE
Problems with full_pipeline

### ISSUE THREAD

**Issue by smith6jt-cop** [mikarubi/voluseg#7]
The requirements need to be updated.

Tifffile is no longer imported from skimage.external in input_channels.py

When using option #2 there is no prompt or other method to enter 'img_dir' so:

Traceback (most recent call last):
  File "/home/smith6jt/CSE/full_pipeline/run_pipeline.py", line 5, in <module>
    pipeline.argparse_wrapper()
  File "/home/smith6jt/CSE/full_pipeline/pipeline/pipeline.py", line 68, in argparse_wrapper
    main(args.config_dir)
  File "/home/smith6jt/CSE/full_pipeline/pipeline/pipeline.py", line 20, in main
    img_dirs = glob.glob(join(config['img_dir'], '**', '*.tif*'), recursive=True)
KeyError: 'img_dir'

Manually adding to config gives:
Traceback (most recent call last):
  File "/home/smith6jt/CSE/full_pipeline/run_pipeline.py", line 5, in <module>
    pipeline.argparse_wrapper()
  File "/home/smith6jt/CSE/full_pipeline/pipeline/pipeline.py", line 68, in argparse_wrapper
    main(args.config_dir)
  File "/home/smith6jt/CSE/full_pipeline/pipeline/pipeline.py", line 55, in main
    mask_dirs = segmentation(seg_dir, config)
  File "/home/smith6jt/CSE/full_pipeline/pipeline/segmentation/run_segmentation.py", line 22, in segmentation
    get_input_channels(img_dir, input_channel_index)
  File "/home/smith6jt/CSE/full_pipeline/pipeline/segmentation/input_channels.py", line 55, in get_input_channels
    image = imread(img_dir)
  File "/home/smith6jt/anaconda3/envs/SegEval/lib/python3.9/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/smith6jt/anaconda3/envs/SegEval/lib/python3.9/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/home/smith6jt/anaconda3/envs/SegEval/lib/python3.9/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/smith6jt/anaconda3/envs/SegEval/lib/python3.9/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/smith6jt/anaconda3/envs/SegEval/lib/python3.9/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/home/smith6jt/anaconda3/envs/SegEval/lib/python3.9/site-packages/imageio/core/imopen.py", line 223, in imopen
    raise err_type(err_msg)
ValueError: ImageIO does not generally support reading folders. Limited support may be available via specific plugins. Specify the plugin explicitly using the `plugin` kwarg, e.g. `plugin='DICOM'`

**Comment by mikarubi** [comment]
I wonder if you have the wrong pipeline? This pipeline does not have input_channels.py

**Comment by smith6jt-cop** [comment]
I’m not sure how this ended up here. It was intended for the CellSegmentationEvaluator repo. Apologies
